# Generated by Django 5.0.2 on 2024-02-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
